### ISSUE TITLE
UnitTests on Windows -  'tuple' object has no attribute 'replace'

### ISSUE THREAD

**Issue by patrickwolf** [shotgunsoftware/python-api#74]
Error occurring when running the unit tests on Windows with Python 2.7.8:

```
Error
Traceback (most recent call last):
  File "C:\dev\shotgun\python_api3\tests\test_api.py", line 378, in test_share_thumbnail
    shot_path = _get_path(shot_url)
  File "C:\dev\shotgun\python_api3\tests\test_api.py", line 1639, in _get_path
    return os.path.join(url[:4])
  File "C:\Python27\lib\ntpath.py", line 64, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Python27\lib\ntpath.py", line 115, in splitdrive
    normp = p.replace(altsep, sep)
AttributeError: 'tuple' object has no attribute 'replace'
```

**Comment by mutsp** [comment]
How do you resolve that error?
